USE [master]
GO
/****** Object:  Database [db_TrustPay]    Script Date: 30.04.2025 19:11:03 ******/
CREATE DATABASE [db_TrustPay]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_TrustPay', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\db_TrustPay.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'db_TrustPay_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\db_TrustPay_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [db_TrustPay] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_TrustPay].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [db_TrustPay] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [db_TrustPay] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [db_TrustPay] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [db_TrustPay] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [db_TrustPay] SET ARITHABORT OFF 
GO
ALTER DATABASE [db_TrustPay] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [db_TrustPay] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [db_TrustPay] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [db_TrustPay] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [db_TrustPay] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [db_TrustPay] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [db_TrustPay] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [db_TrustPay] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [db_TrustPay] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [db_TrustPay] SET  ENABLE_BROKER 
GO
ALTER DATABASE [db_TrustPay] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [db_TrustPay] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [db_TrustPay] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [db_TrustPay] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [db_TrustPay] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [db_TrustPay] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [db_TrustPay] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [db_TrustPay] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [db_TrustPay] SET  MULTI_USER 
GO
ALTER DATABASE [db_TrustPay] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [db_TrustPay] SET DB_CHAINING OFF 
GO
ALTER DATABASE [db_TrustPay] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [db_TrustPay] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [db_TrustPay] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [db_TrustPay] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [db_TrustPay] SET QUERY_STORE = OFF
GO
USE [db_TrustPay]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 30.04.2025 19:11:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Accounts]    Script Date: 30.04.2025 19:11:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Accounts](
	[AccountID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NULL,
	[Balance] [money] NOT NULL,
	[Currency] [varchar](15) NOT NULL,
	[AccountType] [varchar](40) NOT NULL,
	[CreatedAt] [datetime] NOT NULL,
 CONSTRAINT [PK__Accounts__349DA5862AFCF176] PRIMARY KEY CLUSTERED 
(
	[AccountID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Transactions]    Script Date: 30.04.2025 19:11:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Transactions](
	[TransactionID] [int] IDENTITY(1,1) NOT NULL,
	[FromAccountID] [int] NULL,
	[ToAccountID] [int] NULL,
	[Amount] [money] NOT NULL,
	[Currency] [varchar](15) NOT NULL,
	[TransactionDate] [datetime] NOT NULL,
	[TransactionType] [varchar](30) NOT NULL,
 CONSTRAINT [PK__Transact__55433A4BAD92DC03] PRIMARY KEY CLUSTERED 
(
	[TransactionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 30.04.2025 19:11:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [nvarchar](40) NOT NULL,
	[Password] [varchar](40) NOT NULL,
	[Email] [varchar](60) NOT NULL,
	[CreatedAt] [datetime] NOT NULL,
 CONSTRAINT [PK__Users__1788CCAC2C6FA15E] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_Accounts_UserID]    Script Date: 30.04.2025 19:11:03 ******/
CREATE NONCLUSTERED INDEX [IX_Accounts_UserID] ON [dbo].[Accounts]
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Transactions_FromAccountID]    Script Date: 30.04.2025 19:11:03 ******/
CREATE NONCLUSTERED INDEX [IX_Transactions_FromAccountID] ON [dbo].[Transactions]
(
	[FromAccountID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Transactions_ToAccountID]    Script Date: 30.04.2025 19:11:03 ******/
CREATE NONCLUSTERED INDEX [IX_Transactions_ToAccountID] ON [dbo].[Transactions]
(
	[ToAccountID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__Users__C9F28456A2ADCB3A]    Script Date: 30.04.2025 19:11:03 ******/
CREATE UNIQUE NONCLUSTERED INDEX [UQ__Users__C9F28456A2ADCB3A] ON [dbo].[Users]
(
	[UserName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Accounts]  WITH CHECK ADD  CONSTRAINT [FK__Accounts__UserID__3A81B327] FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserID])
GO
ALTER TABLE [dbo].[Accounts] CHECK CONSTRAINT [FK__Accounts__UserID__3A81B327]
GO
ALTER TABLE [dbo].[Transactions]  WITH CHECK ADD  CONSTRAINT [FK__Transacti__FromA__3D5E1FD2] FOREIGN KEY([FromAccountID])
REFERENCES [dbo].[Accounts] ([AccountID])
GO
ALTER TABLE [dbo].[Transactions] CHECK CONSTRAINT [FK__Transacti__FromA__3D5E1FD2]
GO
ALTER TABLE [dbo].[Transactions]  WITH CHECK ADD  CONSTRAINT [FK__Transacti__ToAcc__3E52440B] FOREIGN KEY([ToAccountID])
REFERENCES [dbo].[Accounts] ([AccountID])
GO
ALTER TABLE [dbo].[Transactions] CHECK CONSTRAINT [FK__Transacti__ToAcc__3E52440B]
GO
USE [master]
GO
ALTER DATABASE [db_TrustPay] SET  READ_WRITE 
GO
